apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-koa
  namespace: nodejs-koa
  labels:
    app: nodejs-koa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-koa
  template:
    metadata:
      labels:
        app: nodejs-koa
    spec:
      containers:
      - name: nodejs-koa
        image: nodejs-koa
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
      restartPolicy: Always
