apiVersion: v1
kind: Service
metadata:
  name: nodejs-koa
  namespace: nodejs-koa
  labels:
    app: nodejs-koa
spec:
  type: ClusterIP
  selector:
    app: nodejs-koa
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
